# -*- coding: utf-8 -*-
"""populartiktoksongs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YsjYKw_nWYT4mmKRyKEQ_zivhw1hBnV5
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/tiktok/TikTok_songs_2021.csv')

data.head()

data.columns

data.tail()

data.describe()

data.columns

to_drop = [  'artist_pop', 'album', 'track_pop',
        'energy',  'mode', 'key', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature']
data.drop(to_drop,inplace=True, axis=1)

data.head()

data.tail()

data.columns

sns.relplot(x ='danceability',y = 'loudness',data = data)